---
functional: #функциональное
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары # Товары можно отфильтровать по названию, рейтингу, цене со скидкой и без
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре. # Список товаров можно выводить таблицей, он доступен и авторизованному и неавторизованному пользователю
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины #  Из корзины можно оформить заказ, перейти на страницу оплаты, вернуться обратно к списку товаров
non-functional: #нефункциональное
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  # требование, которое пересекается с последними тремя - Сайт должен быть доступен и корректно отображаться на различных устройствах
  - 
implicit: #неявное
  - Стоимость и описание товара должны отображаться в разных валютах в зависимости от выбранного языка
  - Пользователь должен иметь возможность оформить заказ без авторизации
  - Пользователь должен иметь возможность регистрации в ИМ
  - При посещении сайта должна появляться надпись принятия cookie файлов
  - После добавления товара в корзину должно появляться сообщение об этом
  - Изображения товара на сайте имеют размер не более 200 кБ
  - Данный интернет магазин работает, как SPA приложение
  - На странице товара пользователь может перейти по ссылке в категорию товара
  - Корзина хранится в сессии браузера

