---
functional: #функциональное
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional: #нефункциональное
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен и корректно отображаться на различных устройствах
  - 
implicit: #неявное
  - Стоимость и описание товара должны отображаться в разных валютах в зависимости от выбранного языка
  - Товары можно отфильтровать по рейтингу
  - При оформления заказа без авторизации необходимо указывать телефон
  - При регистрации указывается контактный телефон и email
  - При посещении сайта должна появляться надпись принятия cookie файлов
  - После добавления товара в корзину должно появляться сообщение об этом
  - Список товаров можно выводить таблицей
  - Список товаров доступен и авторизованному и неавторизованному пользователю
  - Изображения товара на сайте имеют размер не более 200 кБ
  - Данный интернет магазин работает, как SPA приложение
  - На странице товара пользователь может перейти по ссылке в категорию товара
  - Корзина хранится в сессии браузера
  - Из корзины можно оформить заказ и перейти на страницу оплаты
