---
functional: #функциональное
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional: #нефункциональное
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах
  - 
implicit: #неявное
  - Стоимость товара должна отображаться в разных валютах в зависимости от языка
  - Товары можно отфильтровать по рейтингу
  - Для оформления заказа требуется быть зарегистрированным пользователем
  - При регистрации указывается контактный телефон и email
  - При посещении сайта должна появляться надпись принятия cookie файлов
  - После добавления товара в корзину должно появляться сообщение об этом
  - Список товаров можно выводить таблицей
